trigger: none


pool: SAgent


jobs:
  - job: initandvalidate
    displayName: init and Validate
    steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'S_service_connection'
          backendAzureRmStorageAccountName: 'stgsonal11'
          backendAzureRmContainerName: 'contsonal'
          backendAzureRmKey: 'terraform.tfstate'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'validate'
  - job: terraformplan
    displayName: terraform plan
    pool: SAgent
    steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'S_service_connection'
          backendAzureRmStorageAccountName: 'stgsonal11'
          backendAzureRmContainerName: 'contsonal'
          backendAzureRmKey: 'terraform.tfstate'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'S_service_connection'


