trigger:
- main
- feature/*

pool: SAgent

stages:
  - stage: Build
    displayName: Build Karna hai
    jobs:
      - job: terraformInitValidate
        displayName: Init & Validate chalana hai
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'S_service_connection'
              backendAzureRmStorageAccountName: 'sanjaystgg'
              backendAzureRmContainerName: 'sanjaycontainer'
              backendAzureRmKey: 'sanjay.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
      # - job: ManualValidation
      #   displayName: Manual Validation karna h
      #   dependsOn: terraformInitValidate
      #   pool: server
      #   steps:
      #   - task: ManualValidation@1
      #     inputs:
      #       notifyUsers: 'cloud.sanjaysingh@gmail.com'
      # - job: TerraformApply
      #   displayName: Terraform Apply karna hai
      #   dependsOn: ManualValidation
      #   steps:
      #   - task: TerraformTask@5
      #     inputs:
      #       provider: 'azurerm'
      #       command: 'init'
      #       backendServiceArm: 'S_service_connection'
      #       backendAzureRmStorageAccountName: 'sanjaystgg'
      #       backendAzureRmContainerName: 'sanjaycontainer'
      #       backendAzureRmKey: 'sanjay.tfsate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'S_service_connection'

  
