trigger:
- main

pool: SAgent

stages:
  - stage: 
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

      - job: 
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'S_service_connection'
            backendAzureRmStorageAccountName: 'sanjaystg111341'
            backendAzureRmContainerName: 'sanjaycntr1'
            backendAzureRmKey: 'terrafor.tfstate'