trigger:
- main
- feature/*

pool: SAgent

stages:
  - stage: Build
    displayName: Build Karna hai
    jobs:
      - job: terraformInitValidate
        displayName: Init & Validate chalana hai
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'S_service_connection'
              backendAzureRmStorageAccountName: 'ranjeetstg1234'
              backendAzureRmContainerName: 'ranjeetcontainer'
              backendAzureRmKey: 'sanjay.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'

      - job: ManualValidation
        displayName: Manual Validation karna h
        dependsOn: terraformInitValidate
        pool: server
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'cloud.sanjaysingh@gmail.com'

  
