trigger:
- main
- feature/*

pool: SAgent

stages:
  - stage: TerraformInitFmtValidate
    displayName: TerraformInitFmtValidate
    jobs:
      - job: terraformInitFMTValidate
        displayName: InitFmtValidate chalana hai
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'